# Generated by Django 4.1.3 on 2022-11-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='personal_foto',
            field=models.ImageField(upload_to='director/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(max_length=100, verbose_name='Заголовок фильма'),
        ),
    ]
